source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:weddingwire/specs-ios.git'
platform :ios, '9.0'

use_frameworks!

def private_pods
  pod 'WWAppearance', '~> 1.2.0'
  pod 'WWRequestKit', :git => 'git@github.com:weddingwire/WWRequestKit.git', :branch => 'master'
end

def shared_pods
	pod 'SlackTextViewController'
	pod 'SnapKit'
end

def testing_pods
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '~> 3.2.0'

  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end

target 'WWForums' do 
	shared_pods
	private_pods
end

target 'WWForumsTests' do
	shared_pods
	testing_pods
end