# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

use_frameworks!

def shared_pods
    pod 'SnapKit'
    pod 'ObjectMapper'
    pod 'BluetoothKit'
end

def testing_pods
    pod 'Quick', '~> 0.9.0'
    pod 'Nimble', '~> 3.2.0'
end

target 'BluetoothTutorial' do
    shared_pods
end


target 'BluetoothTutorialTests' do
    shared_pods
    testing_pods
end